# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170730_1127'),
        ('main_app', '0002_auto_20170728_1338'),
    ]

    operations = [
    ]
